Add CLI params support
HTD-Health/ai-mask-model pull request #9
Opened 2021-01-22 23:15 UTC by rpoltorak

It allows to run experiments easily using CLI params like for example:
```bash
python mask_classifier.py --gpus 1 --batch_size 32 --learning_rate 0.001
```

2021-01-31 18:12 UTC, GrivIN requested changes
Actually, couple of comments
btw. can we require type annotations?

2021-01-31 18:12 UTC, GrivIN commented on mask_detector/datasets/masked_face_net.py
> +        return len(self.dataFrame.index)
you can check len of DataFrame (skipping index)
```suggestion
        return len(self.dataFrame)
```

2021-01-31 18:12 UTC, GrivIN commented on mask_detector/datasets/masked_face_net.py
> +        self.dataFrame = pd.read_csv(csv_file)
nit: can we use snake_case style?

2021-01-31 18:12 UTC, GrivIN commented on mask_detector/mask_classifier.py
>      def __init__(self, net, learning_rate=1e-3):
can we use something readable instead `1e-3`

2021-01-31 18:12 UTC, GrivIN commented on mask_detector/mask_classifier.py
> +        return {'loss': loss, 'accuracy': self.accuracy(out, y)}
I do not like dictionaries returned from functions, can we use data classes here or it is a framework requirement to have dicts here?

2021-01-31 18:12 UTC, GrivIN commented on mask_detector/mask_classifier.py
> +        return {'loss': loss, 'accuracy': self.accuracy(out, y)}
dataclasses are possible here?

2021-01-31 18:12 UTC, GrivIN commented on mask_detector/mask_classifier.py
> +        return {'loss': loss, 'accuracy': self.accuracy(out, y)}
dataclasses are possible here?

2021-02-02 00:01 UTC, jedrzejpolaczek requested changes

2021-02-02 00:01 UTC, jedrzejpolaczek commented on mask_detector/models/mobile_net_v2.py
> +        x = self.classifier(x)
Would be nice to have more meaningful names for variables.

2021-02-02 00:01 UTC, jedrzejpolaczek commented on mask_detector/models/mobile_net_v2.py
> +import torch
Nice and clean!

2021-02-02 00:01 UTC, jedrzejpolaczek commented on mask_detector/datasets/masked_face_net.py
> +"""
I also do not get the name. Why `masked face net`?

2021-02-06 14:37 UTC, rpoltorak commented on mask_detector/models/basic_cnn.py
> -            Softmax()
Because It's better to use Sigmoid function to binary classification problems. Softmax is better for multi-classification. This is the interesting article that explains a bit: http://web.stanford.edu/~nanbhas//blog/sigmoid-softmax.html

2021-02-06 14:41 UTC, rpoltorak commented on mask_detector/mask_classifier.py
> +        return {'loss': loss, 'accuracy': self.accuracy(out, y)}
Maybe, but this is not necessary at this moment because I removed this and return only loss value (everything else should be logged independently by using `self.log()` method.

2021-02-06 14:42 UTC, rpoltorak commented on mask_detector/mask_classifier.py
> +        return {'loss': loss, 'accuracy': self.accuracy(out, y)}
Maybe, but this is not necessary at this moment because I removed this and return only loss value (everything else should be logged independently by using self.log() method.

2021-02-06 14:42 UTC, rpoltorak commented on mask_detector/mask_classifier.py
> +        return {'loss': loss, 'accuracy': self.accuracy(out, y)}
Maybe, but this is not necessary at this moment because I removed this and return only loss value (everything else should be logged independently by using self.log() method.

2021-02-06 14:42 UTC, rpoltorak commented on mask_detector/mask_classifier.py
>      def __init__(self, net, learning_rate=1e-3):
Done :+1:

2021-02-06 14:43 UTC, rpoltorak commented on mask_detector/datasets/masked_face_net.py
> +        self.dataFrame = pd.read_csv(csv_file)
Of course :)

2021-02-06 14:43 UTC, rpoltorak commented on mask_detector/datasets/masked_face_net.py
> +        return len(self.dataFrame.index)
Good point! Changed. I'm pretty sure that using `len(self.data_frame.index)` is a little bit more performant but `len(self.data_frame)` is definitely much cleaner.

2021-02-06 14:48 UTC, rpoltorak commented on mask_detector/datasets/masked_face_net.py
> +""" Dataset module
That's good point, you're right. However, it sounds like a separate task, so I'm gonna create a separate task for that.

2021-02-06 14:52 UTC, rpoltorak commented on mask_detector/datasets/masked_face_net.py
> +            Resize(image_size),  # for MobileNetV2 - set image size to 256
This is indeed a good one. Do you have any idea how we could name that? We need to think about naming that kind of combinations of dataset and model. I can't come up with a name for a combination of MobileNetV2 and MaskedFaceNet :)

2021-02-06 15:06 UTC, rpoltorak commented on mask_detector/datasets/masked_face_net.py
> +"""
Because it's the name of our current dataset. MaskedFaceNet :)

2021-02-06 15:09 UTC, rpoltorak commented on mask_detector/models/basic_cnn.py
>  class BasicCNN(Module):
I love that idea. Created separate README.md file in models directory. You could check this here: `mask_detector/models/README.md`

2021-02-06 15:09 UTC, rpoltorak commented on mask_detector/models/mobile_net_v2.py
> +        x = self.classifier(x)
That's totally true. Changed to `output`. Hope it's clear now :)

2021-02-08 12:41 UTC, azjawinski approved these changes
Looks great 💙 

Added some picky comments, but probably some of them will be fixed when I finally propose some collab tool and the project structure 😞 Because of this I'm already giving approve ✅

2021-02-08 12:41 UTC, azjawinski commented on mask_detector/mask_classifier.py
>  class MaskClassifier(LightningModule):
Hmm, probably it would be convenient to prepare some basic, semi-generic class for our DataModule.
It should define all the common operations for the task we have (image-processing), as probably most of them will be the same between different models.

Then we should extend this base class and overwrite specific methods for each Model we have (choosing correct datasets, defining some transformations etc).

What do you think?

2021-02-08 12:41 UTC, azjawinski commented on mask_detector/models/README.md
> +| MobileNetV2 | max_epochs=10<br>batch_size=32<br>learning_rate=0.001 | 0.1449 | 0.9794 |
Having only loss and recall can be very misleading without having the precision as well.

[Recall does not inform about any false positives](https://en.wikipedia.org/wiki/Precision_and_recall). I suppose you have checked the dataset and if classes are properly balanced.

We have low loss value - though it does not mean anything. We do not know how to interpret this, or is loss `0.1` much better than `0.2`. This is why usually additionally `accuracy` is presented.
On its own accuracy is very risky metric (without precision and recall data we could have a 99% accuracy when model is e.g. always outputting the same value, but classes were not balanced). 

However, it describes what is the most important in evaluating the model outcome - how accurate the model is in the most intuitive way. If we see Recall / Precision / F1 score of e.g. 0.7 we need to think how to interpret it relating to the dataset, possible predictions etc. If we have an accuracy of 0.8 we already see that 80% of all predictions are correct. **Then** we can investigate other metrics to directly compare models, but that accuracy is the true **goal** anyways.

Also we miss **precision**. Here is a nice presentation what this could lead to (based on the situation from a shooting range):
![image](https://user-images.githubusercontent.com/52409053/107220057-310fb280-6a12-11eb-9894-8c196aebf99e.png)

I would opt for tracking all of these metrics (as they are not so slow to compute anyways). We never know when such information could become helpful.

2021-02-08 12:41 UTC, azjawinski commented on mask_detector/models/basic_cnn.py
> +        output = self.linearLayers(output)
We could try to investigate if this generates some calculation efficiency cost. There could be the case that PyTorch is optimizing all the calculations in 1 Sequential layer, that we lose keeping separate Sequentials. Maybe it would be better to store them as arrays and then convert to 1 Sequential?

TBC (To Be Checked) though, it may be not a problem at all.

2021-03-01 17:09 UTC, KonradNojman commented
@rpoltorak Will you be adding something more to this PR, or we can merge it and @azjawinski will work on this topic in the new PRs?

2021-03-08 12:43 UTC, azjawinski commented
Closing this PR, I'm taking this over after Remek.
Comments will be implemented (and further reviewed) in a separate PR.

2021-03-08 12:44 UTC, merged